dist: xenial

language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: "3.8"
      env: TOXENV=py38
      deploy:

    - os: linux
      sudo: required
      python: "3.7"
      env: TOXENV=py37

    - os: linux
      sudo: required
      python: "3.6"
      env: TOXENV=py36
      deploy:

    - os: linux
      sudo: required
      python: "3.5"
      env: TOXENV=py35
      deploy:

    - os: osx
      osx_image: xcode10.2    # Python 3.7.2 running on macOS 10.14.3
      language: generic
      env: TOXENV=py37
      before_install:
        - pip3 install virtualenv
        - virtualenv env -p python3
        - source env/bin/activate
      deploy:

install:
  - pip install --upgrade setuptools
  - pip install -r tests/requirements.txt
  - pip install .

script:
  - coverage run -m unittest discover

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "dwtools"
  password:
    secure: "XUs9pXWe+x7YN0lGC1xlgvGODxIhu2CRAZyWWqep+GZCJVGXwxYTXYpPsCOY7N1zIx+WD2zYTvzAMmU5eB7DBgrZYxsi+ck06KizL0Vcxnzyg3oU0Uk5uSA0KH2nI3+BbhA7lfYbLjiWuO3ALGqArpnMC5xrCwt0WUuOeCmaT8hNifADxhTmdadyhA3qWjehsaokeyeu8xHT02pEJ3vBJWew6YSOjkz4oXvq9x43VlwINRVPt96JkRj1z0CF0Oj2LBgZ+8B4zbzPswBsN23bxtbAzQc+KvMzT4lDjdyZdADnOAuYwDQoOU5CtNA7hLLH4OpzZQeqJfT3yTD4wLwqn2EuB7e3Vcesvx8qMm2iEHTc0RmIq3lZAVMqlbizNTgl3qVayExvwNmRV7AGYtFU1q2WNJuQFwBl4A8KJct68pYx/umyymrVKNlli1VbahjVUwqWYKhddUe1nXTtfN7I6OKTuC4m/j/yuzqn1qdPv1cJiBjj+ZnOe5oym8rbtWx5rNNsD+SQrng7gMwdkw85tCYlWRZvVQ8CpnoDqAKkKjFGIhm6Drzx6uVaMFDgYF4VGvIK///sw56upfmM0eYR0bzwWamQ80c3Xw/MqXKF2Giq1clYMyd5mivrv3V2iosPBEd6u6i3IUEdFRx2GYsMVbdto5RlvIBvsJJfcDglLxA="
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
